# .github/workflows/ci.yml

name: CI (Pytest + Pylint)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      # Change to app_interface directory
      - name: Change directory to app_interface
        run: cd app_interface

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run pytest
      - name: Run pytest
        run: |
          pytest -v --maxfail=1 --disable-warnings

  lint:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      # Change to app_interface directory
      - name: Change directory to app_interface
        run: cd app_interface

      # Install dependencies (including pylint)
      - name: Install dependencies + pylint
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      # Run pylint on the entire package
      - name: Run pylint
        run: |
          # Run pylint against the 'app_interface' package
          pylint app_interface --rcfile=.pylintrc || true

      # Save Pylint score as an output
      - name: Extract Pylint score
        id: pylint-score
        run: |
          SCORE=$(pylint app_interface --rcfile=.pylintrc | grep "Your code has been rated at" || echo "")
          echo "pylint_score=$SCORE" >> $GITHUB_OUTPUT
