
name: CI (Pytest)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        working-directory: app_interface
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run pytest
      - name: Run pytest
        working-directory: app_interface
        run: |
          pytest -v --maxfail=1 --disable-warnings
